
USE WAREHOUSE FRAUD_WH;
USE DATABASE FRAUD_DB;
USE SCHEMA RAW;

SELECT
    COUNT(*) AS total_transactions,
    SUM(CLASS) AS fraud_count,
    ROUND(SUM(CLASS) * 100.0/ COUNT(*), 4)AS fraud_rate_pct
FROM TRANSACTIONS;

SELECT 
    CASE 
        WHEN AMOUNT < 10 THEN '0-10'
        WHEN AMOUNT < 50 THEN '10-50'
        WHEN AMOUNT < 100  THEN '50-100'
        WHEN AMOUNT < 500  THEN '100-500'
        ELSE '500+'
    END AS amount_bucket,
    COUNT(*) AS txn_count,
    SUM(CLASS) AS fraud_count,
    ROUND(SUM(CLASS)* 100 /COUNT(*),4) AS fraud_rate_pct
FROM TRANSACTIONS
GROUP BY 1
ORDER BY MIN(AMOUNT);

SELECT
  CASE
    WHEN AMOUNT < 10 THEN '0-10'
    WHEN AMOUNT < 50 THEN '10-50'
    WHEN AMOUNT < 100 THEN '50-100'
    WHEN AMOUNT < 500 THEN '100-500'
    ELSE '500+'
  END AS amount_bucket,
  CASE WHEN CLASS = 1 THEN 'Fraud' ELSE 'Normal' END AS txn_type,
  COUNT(*) AS txn_count
FROM TRANSACTIONS
GROUP BY 1, 2;



SELECT
    TIME_SEC,
    AMOUNT,
    CLASS,
    SUM(CLASS) OVER (ORDER BY TIME_SEC) AS cumulative_fraud_count,
    ROUND(
        SUM(CLASS) OVER (ORDER BY TIME_SEC)*100.0
        / ROW_NUMBER() OVER( ORDER BY TIME_SEC), 4
    ) AS running_fraud_rate_pct
FROM TRANSACTIONS
ORDER BY TIME_SEC
LIMIT 3000;

ALTER TABLE TRANSACTIONS CLUSTER BY (TIME_SEC);


SELECT SYSTEM$CLUSTERING_INFORMATION('TRANSACTIONS', '(TIME_SEC)');
    