CREATE WAREHOUSE IF not exists fraud_wh
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS FRAUD_DB;
CREATE SCHEMA IF NOT EXISTS FRAUD_DB.RAW;

USE WAREHOUSE FRAUD_WH;
USE DATABASE FRAUD_DB;
USE SCHEMA RAW;


CREATE OR REPLACE TABLE TRANSACTIONS (
  TIME_SEC FLOAT,
  V1 FLOAT,
  V2 FLOAT,
  V3 FLOAT,
  V4 FLOAT,
  V5 FLOAT,
  V6 FLOAT,
  V7 FLOAT,
  V8 FLOAT,
  V9 FLOAT,
  V10 FLOAT,
  V11 FLOAT,
  V12 FLOAT,
  V13 FLOAT,
  V14 FLOAT,
  V15 FLOAT,
  V16 FLOAT,
  V17 FLOAT,
  V18 FLOAT,
  V19 FLOAT,
  V20 FLOAT,
  V21 FLOAT,
  V22 FLOAT,
  V23 FLOAT,
  V24 FLOAT,
  V25 FLOAT,
  V26 FLOAT,
  V27 FLOAT,
  V28 FLOAT,
  AMOUNT FLOAT,
  CLASS NUMBER(1,0)
);


SELECT COUNT(*) AS row_count FROM transactions;